//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoProgra6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdicionesxCliente
    {
        public int idAdicionesxCliente { get; set; }
        public Nullable<int> idAdicion { get; set; }
        public Nullable<int> idCliente { get; set; }
    
        public virtual Adiciones Adiciones { get; set; }
        public virtual Clientes Clientes { get; set; }
    }
}
