//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoProgra6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegistrosPolizas
    {
        public int idRegistroPoliza { get; set; }
        public int idCoberturaPoliza { get; set; }
        public int idCliente { get; set; }
        public Nullable<decimal> montoAsegurado { get; set; }
        public Nullable<decimal> porcentajeCobertura { get; set; }
        public Nullable<int> numeroAdiciones { get; set; }
        public Nullable<decimal> montoAdiciones { get; set; }
        public Nullable<decimal> primaAntesImpuestos { get; set; }
        public Nullable<decimal> impuestos { get; set; }
        public Nullable<decimal> primaFinal { get; set; }
    
        public virtual Clientes Clientes { get; set; }
        public virtual CoberturaPolizas CoberturaPolizas { get; set; }
    }
}
